"""Add Department

Revision ID: 81da44cdb943
Revises: beff6ee79820
Create Date: 2025-11-04 14:01:13.938213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81da44cdb943'
down_revision = 'beff6ee79820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
